# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read | write
      contents: read
      packages: write

    steps:
      - name: Print GITHUB_ACTOR
        run: echo "The actor is ${{ github.actor }}"


      - uses: actions/checkout@v4

      - name: Set up JDK 21  # 或 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # 官方推荐稳定版本
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven

      #      - name: Clean before deploy
      #        run: |
      #          mvn clean
      #          rm -rf ${HOME}/runner/.m2/repository/com/shiny-waddle/helloSpring

      - name: Configure Maven
        run: |
          mkdir -p ~/.m2
          chmod 700 ~/.m2
          cat << EOF > ~/.m2/settings.xml
          <settings>
              <servers>
                  <server>
                      <id>github</id>
                      <username>\${env.GITHUB_ACTOR}</username>
                      <password>\${env.GITHUB_TOKEN}</password>
                  </server>
              </servers>
              <localRepository>\${env.HOME}/.m2/repository</localRepository>
          </settings>
          EOF

      - name: Build and Deploy
        # 自动查找 pom.xml 文件
        run: |
          POM_PATH=$(find . -name pom.xml -not -path '*/target/*' | head -n 1)
          mvn -e -B deploy --file ${POM_PATH}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


